backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "dogs"
    label: "Nasze psy"
    folder: "src/pages/dogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "officialName"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "dogs-page"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Zdjęcie główne", name: image, widget: image, required: false}
      - {label: "Nazwa", name: "officialName", widget: "string"}
      - {label: "Rodowód", name: "lineage", widget: "string"}
      - {label: "Imię domowe", name: "homeName", widget: "string", required: false}
      - {label: "Płeć", name: "gender", widget: "select", options: [{ label: "Pies", value: "male" }, { label: "Suka", value: "female" }, {label: 'Weteran', value: "veteran"}, {label: 'Odszedł', value: "gone"}]}
      - {label: "Data urodzenia", name: "birthDate", widget: "date", default: "", required: false}
      - {label: "Osiągnięcia", name: "achievements", widget: list}
      - {label: "Galeria", name: "galleryImages", widget: list, fields: [{label: Image, name: image, widget: image, required: false}, {required: false, default: "", label: "Podpis", name: "description", widget: string}]}
      - {label: "Opis", name: "description", widget: "text", required: false}

  - name: "litters"
    label: "Szczenięta"
    folder: "src/pages/puppies/litters"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "litters-page"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Nazwa miotu", name: "title", widget: "string"}
      - {label: "Zdjęcie główne", name: image, widget: image, required: false}
      - {label: "Data urodzenia", name: "birthDate", widget: "date", default: "", required: false}
      - {label: "Rodzice", name: "parents", widget: object, fields: [{default: "", label: "Ojciec", name: "father", widget: string}, {default: "", label: "Matka", name: "mother", widget: string}]}
      - {label: "Szczenięta", name: "puppies", widget: list, fields: [{default: "", label: "Imię", name: "name", widget: string, required: false}, {default: false, label: "Na sprzedaż", name: "available", widget: boolean, required: false}, {label: "Płeć", name: "gender", widget: "select", options: [{ label: "Pies", value: "male" }, { label: "Suka", value: "female" }]}]}
      - {label: "Galeria", name: "galleryImages", widget: list,  fields: [{label: Image, name: image, widget: image, required: false}, {default: "", label: "Podpis", name: "description", widget: string, required: false}]}

  - name: "new-home"
    label: "Pieski w nowym domu"
    folder: "src/pages/puppies/new-home"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "new-home-page"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tytuł postu", name: "title", widget: "string"}
      - {label: "Zdjęcie główne", name: image, widget: image, required: false}
      - {label: "Galeria", name: "galleryImages", widget: list,  fields: [{label: Image, name: image, widget: image, required: false}, {required: false, default: "", label: "Podpis", name: "description", widget: string}]}
      - {label: "Opis", name: "description", widget: "text"}

  - name: "exhibitions"
    label: "Wystawy"
    folder: "src/pages/exhibitions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "officialName"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "exhibitions-page"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Nazwa wystawy", name: "title", widget: "string"}
      - {label: "Zdjęcie główne", name: image, widget: image, required: false}
      - {label: "Data wystawy", name: "exhibitionDate", widget: "date", required: false}
      - {label: "Galeria", name: "galleryImages", widget: list, fields: [{label: Image, name: image, widget: image, required: false}, {required: false, default: "", label: "Podpis", name: "description", widget: string}]}
      - {label: "Wystawione psy", name: "dogs", widget: list, fields: [{label: "Pies", name: "dog", widget: string, required: false}, {required: false, default: [""], label: "Osiągnięcia", name: "achievements", widget: list}]}

  - name: "gallery"
    label: "Galeria"
    folder: "src/pages/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-page"}
      - {label: "Nazwa folderu", name: "title", widget: "string"}
      - {label: "Zdjęcia", name: "galleryImages", widget: list,  fields: [{label: Image, name: image, widget: image}, {required: false, default: "", label: "Podpis", name: "description", widget: string}]}
